
import { Property } from './types';

export const PROPERTIES: Property[] = [
  {
    id: '1',
    name: 'Vinhome Central Park',
    location: 'Bình Thạnh, TP.HCM',
    price: '4.5 Tỷ',
    unitPrice: '95tr/m²',
    beds: 2,
    baths: 2,
    area: '72m²',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
    match: 98,
    isHot: true,
    isVerified: true,
    potential: 8.5,
    description: 'Căn hộ cao cấp với tầm nhìn trực diện công viên 14ha, thiết kế hiện đại, đầy đủ tiện ích.',
    type: 'apartment',
    transaction: 'buy',
    coords: { x: 45, y: 40 }
  },
  {
    id: '2',
    name: 'Metropole Thủ Thiêm',
    location: 'Thủ Thiêm, Quận 2',
    price: '12 Tỷ',
    unitPrice: '160tr/m²',
    beds: 3,
    baths: 2,
    area: '110m²',
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80',
    match: 95,
    isHot: false,
    isVerified: true,
    potential: 9.2,
    description: 'Biểu tượng mới của sự sang trọng tại lõi Thủ Thiêm, view sông Sài Gòn trực diện.',
    type: 'apartment',
    transaction: 'buy',
    coords: { x: 65, y: 55 }
  },
  {
    id: '3',
    name: 'Biệt thự Thảo Điền',
    location: 'Thảo Điền, TP. Thủ Đức',
    price: '85 Tỷ',
    unitPrice: '212tr/m²',
    beds: 5,
    baths: 6,
    area: '400m²',
    image: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=800&q=80',
    match: 92,
    isHot: true,
    isVerified: true,
    potential: 7.8,
    description: 'Không gian sống đẳng cấp, riêng tư tuyệt đối với hồ bơi và sân vườn rộng rãi.',
    type: 'villa',
    transaction: 'buy',
    coords: { x: 30, y: 60 }
  },
  {
    id: '4',
    name: 'Căn hộ Studio Masteri',
    location: 'Thủ Thiêm, Quận 2',
    price: '15 Triệu',
    unitPrice: '450k/m²',
    beds: 1,
    baths: 1,
    area: '35m²',
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80',
    match: 90,
    isHot: false,
    isVerified: true,
    potential: 8.0,
    description: 'Căn hộ nhỏ gọn, đầy đủ nội thất, phù hợp cho người độc thân hoặc chuyên gia.',
    type: 'apartment',
    transaction: 'rent',
    coords: { x: 55, y: 35 }
  },
  {
    id: '5',
    name: 'Nhà phố Verosa Park',
    location: 'Quận 9, TP. Thủ Đức',
    price: '18 Tỷ',
    unitPrice: '120tr/m²',
    beds: 4,
    baths: 4,
    area: '150m²',
    image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=800&q=80',
    match: 88,
    isHot: false,
    isVerified: true,
    potential: 8.2,
    description: 'Nhà phố cao cấp, không gian yên tĩnh, compound an ninh 24/7.',
    type: 'house',
    transaction: 'buy',
    coords: { x: 85, y: 30 }
  },
  {
    id: '6',
    name: 'Đất nền Long Phước',
    location: 'Quận 9, TP. Thủ Đức',
    price: '3.5 Tỷ',
    unitPrice: '35tr/m²',
    beds: 0,
    baths: 0,
    area: '100m²',
    image: 'https://images.unsplash.com/photo-1500382017468-9049fee74a62?auto=format&fit=crop&w=800&q=80',
    match: 85,
    isHot: true,
    isVerified: false,
    potential: 9.5,
    description: 'Lô đất thổ cư vuông vức, gần khu công nghệ cao, tiềm năng tăng giá tốt.',
    type: 'land',
    transaction: 'buy',
    coords: { x: 90, y: 70 }
  },
  {
    id: '7',
    name: 'Chung cư Quận 1 Central',
    location: 'Quận 1, TP.HCM',
    price: '15 Tỷ',
    unitPrice: '180tr/m²',
    beds: 2,
    baths: 2,
    area: '85m²',
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80',
    match: 99,
    isHot: true,
    isVerified: true,
    potential: 9.8,
    description: 'Vị trí vàng ngay lõi trung tâm Quận 1, tầm nhìn không giới hạn.',
    type: 'apartment',
    transaction: 'buy',
    coords: { x: 40, y: 50 }
  }
];
